version: '2.4'
x-database-variable: &database-variables
  SPRING_DATASOURCE_URL: jdbc:mysql://db_orange-talents:3306/orange-talents?createDatabaseIfNotExist=true&autoReconnect=true
services:
  db:
    image: mysql
    container_name: db_orange-talents
    environment:
      MYSQL_ROOT_PASSWORD: harisson
      MYSQL_USER: orange
      MYSQL_PASSWORD: harisson
      MYSQL_DATABASE: orange-talents
    ports:
    - "3306:3306"
    volumes:
    - orange_talents:/var/lib/mysql

  orange-talents:
    container_name: orange-talents
    image: harissonnascimento/orange-talents
    ports:
    - "8080:8080"
    environment:
      <<: *database-variables
    depends_on:
      - db
    restart: always
volumes:
  orange_talents: